Complete overhaul of build scripts strategy

diff --git a/build-scripts/build b/build-scripts/build
--- a/build-scripts/build
+++ b/build-scripts/build
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-set -e
+set -eo pipefail
 
 [ -f ~/.bash_profile ] && source ~/.bash_profile
 
@@ -12,21 +12,62 @@ source $GIT_ROOT/ci-jobs.sh || source $GIT_ROOT/ci-jobs.sh.example
 
 source $BUILD_SCRIPTS_DIR/helpers
 
+try_report_failure() {
+    if [ ! -z $failure_step ]; then
+        echo
+        red_echo "###############"
+        red_echo "BUILD FAILED AT $failure_step"
+        red_echo "###############"
+        echo
+    fi
+}
+
 build() {
     cd $GIT_ROOT
+    job=$1
 
-    steps=$1[@]
-
-    red_echo "### This build will execute the following steps:"
+    # shows the user the name of the steps that the desired job will run
+    steps=${job}[@]
+    red_echo "### $job will execute the following steps:"
     for step in "${!steps}"; do red_echo "- $step"; done
 
+    failure_step=""
     for step in "${!steps}"
-    do execute $step || exit $?; done
+    do
+        [ -f $BUILD_SCRIPTS_DIR/${step}_pre ] &&
+            (execute ${step}_pre || failure_step=${step}_pre)
+        [ ! -z $failure_step ] && break
+
+        execute $step || failure_step=${step}
+        [ ! -z $failure_step ] && break
+
+        [ -f $BUILD_SCRIPTS_DIR/${step}_post ] &&
+            (execute ${step}_post || failure_step=${step}_post)
+        [ ! -z $failure_step ] && break
+    done
+
+    # checks wether an associated ensure job exists
+    ensure_job=""
+    set +u
+    eval [ ! -z \$${job}_ensure ] && ensure_job=${job}_ensure
+    set -u
+
+    # if the ensure job exists, dereference it and run its steps
+    if [ ! -z $ensure_job ]; then
+        steps=${ensure_job}[@]
+        echo
+        red_echo "### ${job}_ensure will execute the following steps:"
+        for step in "${!steps}"; do red_echo "- $step"; done
+
+        for step in "${!steps}"
+        do
+            # if a step fail, ignore it and keep the iteration going
+            (execute $step) || true
+        done
+    fi
+
+    try_report_failure
+    [ -z $failure_step ]
 }
 
-build_with_notify() {
-    (build $1) && execute build-status-notify ||
-            (BUILD_FAILED=true execute build-status-notify && exit 1)
-}
-
-build_with_notify $1
+build $1
